<?php
session_start();
include 'db_connection.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    header("Location: dashboard.php");
    exit();
}

$admin_name = htmlspecialchars($_SESSION['first_name'] . ' ' . $_SESSION['last_name']);
$message = "";
$message_class = "";
$notifications = [];
$messages = [];

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $action = $_POST['action'] ?? '';

    if ($action === 'delete_notification') {
        $notification_id = isset($_POST['notification_id']) ? (int) $_POST['notification_id'] : 0;

        if ($notification_id > 0) {
            $stmt = $conn->prepare("DELETE FROM notifications WHERE notification_id = ?");
            $stmt->bind_param("i", $notification_id);

            if ($stmt->execute()) {
                $message = "Notification deleted successfully.";
                $message_class = "message message-success";
            } else {
                $message = "Unable to delete notification.";
                $message_class = "message message-error";
            }
        }
    }

    if ($action === 'delete_contact_message') {
        $message_id = isset($_POST['message_id']) ? (int) $_POST['message_id'] : 0;

        if ($message_id > 0) {
            $stmt = $conn->prepare("DELETE FROM contact_messages WHERE message_id = ?");
            $stmt->bind_param("i", $message_id);

            if ($stmt->execute()) {
                $message = "Contact message deleted successfully.";
                $message_class = "message message-success";
            } else {
                $message = "Unable to delete contact message.";
                $message_class = "message message-error";
            }
        }
    }
}

$sqlNotifications = "
    SELECT
        n.notification_id,
        n.user_id,
        n.message,
        n.created_at,
        u.first_name,
        u.last_name
    FROM notifications n
    INNER JOIN users u ON n.user_id = u.user_id
    ORDER BY n.notification_id DESC
";
$resultNotifications = $conn->query($sqlNotifications);
if ($resultNotifications) {
    while ($row = $resultNotifications->fetch_assoc()) {
        $notifications[] = $row;
    }
}

$resultMessages = $conn->query("SELECT * FROM contact_messages ORDER BY message_id DESC");
if ($resultMessages) {
    while ($row = $resultMessages->fetch_assoc()) {
        $messages[] = $row;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Notifications</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="admin.css">
</head>
<body>

<div class="top-bar">
    NHS Appointment Booking System | Admin Notifications
</div>

<div class="admin-shell">
    <div class="admin-header-card">
        <h2>Admin Panel</h2>
        <p>Welcome, <?php echo $admin_name; ?>. Review notifications and contact messages.</p>

        <div class="admin-tabs">
            <a class="admin-tab" href="admin_dashboard.php">Overview</a>
            <a class="admin-tab" href="admin_users.php">Users</a>
            <a class="admin-tab" href="admin_doctors.php">Doctors</a>
            <a class="admin-tab" href="admin_appointments.php">Appointments</a>
            <a class="admin-tab active" href="admin_notifications.php">Notifications</a>
            <a class="admin-tab" href="logout.php">Logout</a>
        </div>
    </div>

    <div class="admin-card">
        <h3 class="admin-section-title">System Notifications</h3>
        <p class="admin-section-intro">
            This page shows appointment-related notifications generated by the system.
        </p>

        <?php if (!empty($message)): ?>
            <div class="<?php echo $message_class; ?>">
                <?php echo htmlspecialchars($message); ?>
            </div>
        <?php endif; ?>

        <?php if (!empty($notifications)): ?>
            <div class="table-wrapper">
                <table class="appointments-table">
                    <thead>
                        <tr>
                            <th>Notification ID</th>
                            <th>User</th>
                            <th>Message</th>
                            <th>Created</th>
                            <th>Admin Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($notifications as $notification): ?>
                            <tr>
                                <td><?php echo htmlspecialchars($notification['notification_id']); ?></td>
                                <td><?php echo htmlspecialchars($notification['first_name'] . ' ' . $notification['last_name']); ?> (ID: <?php echo htmlspecialchars($notification['user_id']); ?>)</td>
                                <td><?php echo htmlspecialchars($notification['message']); ?></td>
                                <td><?php echo htmlspecialchars($notification['created_at']); ?></td>
                                <td>
                                    <form method="POST" onsubmit="return confirm('Delete this notification?');">
                                        <input type="hidden" name="action" value="delete_notification">
                                        <input type="hidden" name="notification_id" value="<?php echo (int)$notification['notification_id']; ?>">
                                        <button type="submit" class="small-button danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message message-info">No notifications found.</div>
        <?php endif; ?>

        <h3 class="admin-section-title" style="margin-top: 30px;">Contact Messages</h3>
        <p class="admin-section-intro">
            This section shows messages submitted through the Contact Us page.
        </p>

        <?php if (!empty($messages)): ?>
            <div class="table-wrapper">
                <table class="appointments-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Full Name</th>
                            <th>Email</th>
                            <th>Subject</th>
                            <th>Message</th>
                            <th>Created</th>
                            <th>Admin Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($messages as $msg): ?>
                            <tr>
                                <td><?php echo htmlspecialchars($msg['message_id']); ?></td>
                                <td><?php echo htmlspecialchars($msg['full_name']); ?></td>
                                <td><?php echo htmlspecialchars($msg['email']); ?></td>
                                <td><?php echo htmlspecialchars($msg['subject']); ?></td>
                                <td><?php echo htmlspecialchars($msg['message']); ?></td>
                                <td><?php echo htmlspecialchars($msg['created_at']); ?></td>
                                <td>
                                    <form method="POST" onsubmit="return confirm('Delete this contact message?');">
                                        <input type="hidden" name="action" value="delete_contact_message">
                                        <input type="hidden" name="message_id" value="<?php echo (int)$msg['message_id']; ?>">
                                        <button type="submit" class="small-button danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message message-info">No contact messages found.</div>
        <?php endif; ?>
    </div>
</div>

<footer class="footer">
    <p>&copy; 2026 NHS Appointment Booking System | Student Project</p>
</footer>

</body>
</html>